name: RDC Consultants
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23227
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ba73b8'
    - '#83317e'
    - '#cc99cb'
    - '#964f92'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
